config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get 'inventary', to: 'home#inventary'
  
  resources :items do
    collection {post :import}
  end
  resources :home do
    collection do
      post :check_50_last_sales
      post :button_find_new_items
      post :button_update_sale_items
      post :button_change_status_new_to_main
      post :button_re_create_buy_orders
      post :button_remove_ident_items
      post :button_update_status
      post :button_update_price_bought_items
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection
  def self.send_request(url)
    uri           = URI.parse(url)
    response_json = Net::HTTP.get_response(uri)

    JSON.parse(response_json.body)
  end
end

app/models/constant.rb
class Constant
  NEW_ITEMS_STATUS               = 'new'.freeze
  MAIN_ITEMS_STATUS              = 'main'.freeze
  ACTUALLY_MAIN_ITEMS_STATUS     = 'main_actually'.freeze
  NOT_ACTUALLY_MAIN_ITEMS_STATUS = 'main_not_actually'.freeze
  NOT_SALE_ITEMS_STATUS          = 'not sale'.freeze
  SALE_ITEMS_STATUS              = 'sale on'.freeze

  ITEM_HASH_CLASS_ID_KEY         = 'classid'.freeze
  ITEM_HASH_INSTANCE_ID_KEY      = 'instanceid'.freeze
  ITEM_HASH_PRICE_KEY            = 'price'.freeze
  ITEM_HASH_HASH_NAME_KEY        = 'hash_name'.freeze
  ITEM_HASH_BEST_OFFER_KEY       = 'best_offer'.freeze
  ITEM_INFO_HASH_MIN_PRICE_KEY   = 'min_price'.freeze
  HASH_MIN_KEY                   = 'min'.freeze
  HASH_MAX_KEY                   = 'max'.freeze
  HASH_AVERAGE_KEY               = 'average'.freeze

  COUNT_FOUND_ITEMS_TEXT         = 'Found %{count_item} new items!'.freeze
  ITEM_CREATED_TEXT              = 'Item created!'.freeze
  REMOVED_ALL_TRADES_TEXT        = 'Removed all trades!'.freeze
  WAIT_15_SEK_TEXT               = 'Wait 15 sec!'.freeze
  NOT_SALE_ITEMS_UPDATED_TEXT    = 'Items (not sale) in my db updated!'.freeze
  FINISHED_FILLING_TEXT          = 'Finished filling price_of_buy fields!'.freeze
  PUT_UP_ALL_BOUGHT_ITEMS_TEXT   = 'Put up all bought items!'.freeze

  LAST_50_PURCHASES_URL          = 'https://market.dota2.net/history/json/'.freeze
  BEST_BUY_OFFER_URL             = 'https://market.dota2.net/api/BestBuyOffer/'\
                                   '%{class_id}_%{instance_id}/?key=%{your_secret_key}'.freeze
  BEST_SELL_OFFER_URL            = 'https://market.dota2.net/api/BestSellOffer/'\
                                   '%{class_id}_%{instance_id}/?key=%{your_secret_key}'.freeze
  DELETE_ORDERS_URL              = 'https://market.dota2.net/api/DeleteOrders/?key=%{your_secret_key}'.freeze
  CREATE_ORDER_URL               = 'https://market.dota2.net/api/ProcessOrder/'\
                                   '%{class_id}/%{instance_id}/%{price}/?key=%{your_secret_key}'.freeze
  ITEM_LINK_URL                  = 'https://market.dota2.net/item/'\
                                   '%{class_id}-%{instance_id}-%{i_market_hash_name}/'.freeze
  NOT_SALE_ITEMS_URL             = 'https://market.dota2.net/api/GetInv/?key=%{your_secret_key}'.freeze
  SALE_ITEMS_URL                 = 'https://market.dota2.net/api/GetMySellOffers/?key=%{your_secret_key}'.freeze
  ITEM_HISTORY_URL               = 'https://market.dota2.net/api/ItemHistory/'\
                                   '%{class_id}_%{instance_id}/?key=%{your_secret_key}'.freeze
  ITEM_INFORMATION_URL           = 'https://market.dota2.net/api/ItemInfo/'\
                                   '%{class_id}_%{instance_id}/ru/?key=%{your_secret_key}'.freeze
  GET_ORDERS_LOG_URL             = 'https://market.dota2.net/api/GetOrdersLog/?key=%{your_secret_key}'.freeze
  UPDATE_ORDER_URL               = 'https://market.dota2.net/api/UpdateOrder/'\
                                   '%{class_id}/%{instance_id}/%{price}/?key=%{your_secret_key}'.freeze
  SET_PRICE_URL                  = 'https://market.dota2.net/api/SetPrice/%{ui_id}/%{price}/?key=%{your_secret_key}'.freeze
  REMOVE_ALL_URL                 = 'https://market.dota2.net/api/RemoveAll/?key=%{your_secret_key}'.freeze
  UPDATE_INVENTARY_URL           = 'https://market.dota2.net/api/UpdateInventory/?key=%{your_secret_key}'.freeze
end

app/models/item.rb
class Item < ApplicationRecord
  include CheckItems
  include Inventary
  include CreateOrders
  include UpdateStatus
  include ChangeStatus
  include RemoveIdentItems
  include UpdatePriceBoughtItems

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Item.create! row.to_hash
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @not_actually_main_items = Item.where(status: Constant::NOT_ACTUALLY_MAIN_ITEMS_STATUS)
    @actually_main_items     = Item.where(status: Constant::ACTUALLY_MAIN_ITEMS_STATUS).order("price")
    @main_items              = Item.where(status: Constant::MAIN_ITEMS_STATUS)
    @new_items               = Item.where(status: Constant::NEW_ITEMS_STATUS)
    @all_main_items          = @main_items + @actually_main_items + @not_actually_main_items
  end

  def inventary
    @sale_items      = Item.where(status: Constant::SALE_ITEMS_STATUS).order("ui_price")
    @cheap_items     = Item.where('ui_price < ?', 30)
    @expensive_items = Item.where('ui_price > ?', 30)
  end

  def button_update_sale_items
    main_object.update_sale_items_in_my_db

    respond_to do |format|
      format.html { redirect_to inventary_url, notice: 'Sale items is updated!' }
    end
  end

  def button_find_new_items
    main_object.find_new_items(params[:from_price], params[:to_price], params[:count_item])

    respond_to do |format|
      format.html { redirect_to home_index_url, notice: 'Items found!' }
    end
  end

  def button_change_status_new_to_main
    main_object.change_status_new_to_main

    respond_to do |format|
      format.html { redirect_to home_index_url, notice: 'Status changed!' }
    end
  end

  def button_re_create_buy_orders
    main_object.re_create_buy_orders

    respond_to do |format|
      format.html { redirect_to home_index_url, notice: 'Purchase orders re-created!' }
    end
  end

  def button_remove_ident_items
    main_object.remove_ident_items

    respond_to do |format|
      format.html { redirect_to home_index_url, notice: 'The identical items are deleted!' }
    end
  end

  def button_update_status
    main_object.update_status

    respond_to do |format|
      format.html { redirect_to home_index_url, notice: 'Status is updated!' }
    end
  end

  def button_update_price_bought_items
    main_object.update_price_bought_items
    main_object.update_sale_items_in_my_db

    respond_to do |format|
      format.html { redirect_to home_index_url, notice: 'Price of bought items is updated!' }
    end
  end

  private

  def main_object
    @main_object ||= Item.new
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  require 'csv'

  def index
    @items               = Item.all
    @actually_main_items = Item.where(status: Constant::ACTUALLY_MAIN_ITEMS_STATUS).order("price")

    respond_to do |format|
      format.html
      format.csv { send_data @actually_main_items.to_csv }
      format.xls 
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def import
    Item.import(params[:file])

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to home_index_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= render 'partials/input_form_check_items.html' %>
<p>
<%= render 'partials/new_items_list.html' %>
<p>
<%= form_tag(button_change_status_new_to_main_home_index_path, method: 'post') do %>
  <%= submit_tag('Cange status: new => main') %>
<% end %>
<p>
<%= render 'partials/actually_main_items_list.html' %>
<p>
<%= form_tag(button_update_status_home_index_path, method: 'post') do %>
  <%= submit_tag('Update status') %>
<% end %>
<p>
<%= form_tag(button_re_create_buy_orders_home_index_path, method: 'post') do %>
  <%= submit_tag('Re-create buy orders') %>
<% end %>
<p>
<h1>Main Items (actually/not_actually/main) - <%= @all_main_items.size %></h1>
<p>
<%= form_tag(button_remove_ident_items_home_index_path, method: 'post') do %>
  <%= submit_tag('Remove identical items') %>
<% end %>
<p>
<h3>Import data:</h3>
<%= form_tag import_items_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag('Import CSV') %>
<% end %>
<p>
<h3>Export data:</h3>
  <%= link_to "CSV", items_path(format: "csv") %> |
  <%= link_to "Excel", items_path(format: "xls") %>
</p>

app/views/home/inventary.html.erb
<%= form_tag(button_update_price_bought_items_home_index_path, method: 'post') do %>
  <%= submit_tag('UpdatePriceBoughtItems') %>
<% end %>
<br>
<h3>All kinds of sale Items: (count: <%= @sale_items.size %>) </h3>
<br>
<h3>Cheap Items: (count: <%= @cheap_items.size %>) </h3>
<br>
<h3>List extensive Items: (count: <%= @expensive_items.size %>) </h3>
<p>
<%= render 'partials/list_extencive_items.html' %>
<p>

<br>
<%= form_tag(button_update_sale_items_home_index_path, method: 'post') do %>
  <%= submit_tag('Update_sale_items') %>
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CyberBot" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag '/favicon.ico' %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">CyberBot</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Inventary", "/inventary"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
          </p>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Import data:</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/partials/_actually_main_items_list.html.erb
<h1>Actually main Items list (count: <%= Item.where(status: 'main_actually').size %>) </h1>
<table>
  <thead>
    <tr>
      <th>hash_name</th>
      <th>price</th>
      <th>link</th>
      <th>link_destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @actually_main_items.each do |item| %>
      <tr>
        <td><%= item.hash_name %></td>
        <td>&nbsp;<%= item.price %>&nbsp;</td>
        <td><%= link_to 'Link', item.link %>&nbsp;</td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_input_form_check_items.html.erb
<table>
  <tbody>
    <%= form_tag(button_find_new_items_home_index_path, method: "post") do %>
      <tr>
        <th><%= label_tag(:count_item, "Count item:") %>
        <%= text_field_tag(:count_item) %><th>
        &nbsp;
        <th><%= label_tag(:from_price, "From price:") %>
        <%= text_field_tag(:from_price) %><th>
        &nbsp;
        <th><%= label_tag(:to_price,   "To price:") %>
        <%= text_field_tag(:to_price) %><th>
      </tr>
  </tbody>
</table>
      <br>
      <%= submit_tag("Find new items") %>
    <% end %>

app/views/partials/_list_extencive_items.html.erb
<table>
  <thead>
    <tr>
      <th>i_name</th>
      <th>ui_price</th>
      <th>link</th>
    </tr>
  </thead>

  <tbody>
    <% @expensive_items.each do |item| %>
      <tr>
        <td><%= item.i_name %></td>
        <td><%= item.ui_price %></td>
        <td><%= link_to 'Link', item.link %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_list_not_sale_items.html.erb
<h1>Listing not sale Items</h1>
<table>
  <thead>
    <tr>
      <th>ui_id</th>
      <th>i_market_hash_name</th>
      <th>i_market_name</th>
      <th>i_name_color</th>
      <th>i_rarity</th>
      <th>status</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.ui_id %></td>
        <td><%= item.i_market_hash_name %></td>
        <td><%= item.i_market_name %></td>
        <td><%= item.i_name_color %></td>
        <td><%= item.i_rarity %></td>
        <td><%= item.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_list_sale_items.html.erb
<h1>Listing sale Items</h1>
<table>
  <thead>
    <tr>
      <th>i_name</th>
      <th>ui_price</th>
      <th>link</th>
      <th>price_of_buy</th>
    </tr>
  </thead>

  <tbody>
    <% @sale_items.each do |item| %>
      <tr>
        <td><%= item.i_name %></td>
        <td><%= item.ui_price %></td>
        <td><%= link_to 'Link', item.link %></td>
        <td><%= item.price_of_buy %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_main_items_list.html.erb
<h1>Main Items</h1>
<table>
  <thead>
    <tr>
      <th>hash_name</th>
      <th>price</th>
      <th>link</th>
      <th>link_destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @main_items.each do |item| %>
      <tr>
        <td><%= item.hash_name %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Link', item.link %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_new_items_list.html.erb
<h1>New Items (count: <%= @new_items.size %>)</h1>
<table>
  <thead>
    <tr>
      <th>hash_name</th>
      <th>price</th>
      <th>link</th>
      <th>Destroy link</th>
    </tr>
  </thead>

  <tbody>
    <% @new_items.each do |item| %>
      <tr>
        <td><%= item.hash_name %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Link', item.link %>&nbsp;</td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_not_actually_main_items_list.html.erb
<h1>Not Actually main Items list (count: <%= @not_actually_main_items.size %>)</h1>
<table>
  <thead>
    <tr>
      <th>hash_name</th>
      <th>price</th>
      <th>link</th>
      <th>link_destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @not_actually_main_items.each do |item| %>
      <tr>
        <td><%= item.hash_name %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Link', item.link %>&nbsp;</td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>